Use interfaces from dojo cli
dojo/cli-export-project pull request #18
Opened 2018-01-12 13:46 UTC by umaar

**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Uses the interfaces from dojo/cli instead of dojo/interfaces.

Addresses: https://github.com/dojo/meta/issues/223

2018-02-13 16:53 UTC, dylans requested changes

2018-02-13 16:53 UTC, dylans commented on package.json
> +    "@dojo/cli": "~0.4.2",
Switch to 0.6.0 and rerun CI please.

2018-02-16 15:34 UTC, umaar commented
Everything's passing and cli `0.6.1` is specified! Shall we merge?

2018-02-26 15:00 UTC, dylans approved these changes

2018-02-26 15:56 UTC, merged